logo_title: Cracker

style: black

favicon: /favicon.ico

menu:
  # 运维: /maintain
  # PHP: /php
  # LINUX: /linux
  # 关于我: /about
  #Github: https://github.com/sanjinhub

# 做了域名限制，请改成自己的 KEY
# 若关闭valine 设置enable为false
valine:
  enable: false
  appId: VvOtjUgtepPdGr65qWmkXtOE-9Nh9j0Va
  appKey: JcpMXdIzqOXzGO9i7B6lRkIn

highlight:
  enable: true